DROP TABLE IF EXISTS TRADE_TAX;
CREATE TABLE TRADE_TAX (
TRADE_ID INT PRIMARY KEY,
TRADE_NAME VARCHAR(50) NOT NULL,
TRADE_VALUE INT(20) NOT NULL,
TAX_PERCENTAGE INT(8) NOT NULL,
TAX_AMOUNT INT(20) NOT NULL,
VALUE_AFTER_TAX VARCHAR(20) NOT NULL);